dist: xenial
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_install:
  - pip install --user cpp-coveralls

script:
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - mkdir build
  - cd build
  - cmake -DVAJOLET_CPU_TYPE=64NEW -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - cd tests
  - ./Vajolet_unit_test
  - ./Vajolet_search_integration_test
  - cd ..
  - cd src
  - ./Vajolet bench
  
after_success:
  - coveralls --gcov gcov-7 --root .. --gcov-options '\-lp' -e tests -e build/CMakeFiles -e build/googletest-src 
  